version: '3.7'

services:
  treee:
    # image: edgewhere/treee:1.3.12
    build: .
    volumes:
      - data-treee:/home/treee/saved
    ports:
      - 7000:7000
    hostname: treee-1
    container_name: treee-1
    restart: always
    environment:
      HOST: treee-1
      HTTP_PORT: 7000
      INIT_PRIME: 101
      INDEX_PATH: ./saved/treee-1.json
      PERMANENT_INDEX: true

volumes:
  data-treee:
    driver: local
